#!/bin/bash
#BSUB -J mas-gpt2-small
#BSUB -o logs/mas-gpt2-small_%J.out
#BSUB -e logs/mas-gpt2-small_%J.err
#BSUB -q gpua100
#BSUB -n 12
#BSUB -W 24:00
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=4096]"
#BSUB -gpu "num=1:mode=exclusive_process"

module load python3/3.11.3
module load nvhpc/22.11-nompi
module load cuda/11.8

source .venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install -r requirements.txt

python3 -m thesis.mas --config-name gpt2-small-sae.yaml params.samples_to_check=524288 out_path=/work3/s183969/outputs/gpt2-small_sae_store

