name: Publish LaTeX

on:
  push:
    branches:
      - main
      - ci-test
    paths:
      - 'report/**'

jobs:
  publish_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Debug info
        run: |
          ls report
          ls report/sections
          cat report/sections.tex
          echo "GITHUB_REF: $GITHUB_REF"

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          work_in_root_file_dir: true
          root_file: ./report/main.tex
      
      - name: Create artifact1
        uses: actions/upload-artifact@v4
        with:
          name: report1
          path: ./report/main.pdf

      - name: Move PDF to root directory
        run: |
          mkdir -p github_pages/${BRANCH_NAME}
          mv report/main.pdf github_pages/${BRANCH_NAME}/report.pdf
        env:
          BRANCH_NAME: ${{ github.ref_name }}
      
      - name: Create artifact2
        uses: actions/upload-artifact@v4
        with:
          name: report2
          path: github_pages/${BRANCH_NAME}/report.pdf

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAGES_TOKEN }}
          publish_dir: ./github_pages
          publish_branch: github-pages